files:
  - source: /content/en/**/*.md
    ignore:
      - /content/en/privacypolicy.md
      - /content/en/*license.md
    translation: /content/%two_letters_code%/**/%file_name%.md
    languages_mapping:
      two_letters_code:
        pt-BR: pt-BR
        zh-CN: zh-CN
        zh-TW: zh-TW
        zh-HK: zh-HK
        zh-MO: zh-MO
        zh-SG: zh-SG
  - source: /themes/wz2100net/i18n/en.json
    type: "chrome"
    translation: /themes/wz2100net/i18n/%two_letters_code%.json
    update_option: update_as_unapproved
    languages_mapping:
      two_letters_code:
        pt-BR: pt_br
        zh-CN: zh_cn
        zh-TW: zh_tw
        zh-HK: zh_hk
        zh-MO: zh_mo
        zh-SG: zh_sg
